/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as JadwalRouteImport } from './routes/jadwal'
import { Route as PortofolioRouteImport } from './routes/portofolio'
import { Route as OrganisasiRouteImport } from './routes/organisasi'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SiswaRouteImport } from './routes/siswa'
import { Route as AuthenticatedVotingRouteImport } from './routes/_authenticated/voting'
import { Route as AuthenticatedSaranRouteImport } from './routes/_authenticated/saran'
import { Route as AuthenticatedProfilSayaRouteImport } from './routes/_authenticated/profil-saya'
import { Route as AuthenticatedKasRouteImport } from './routes/_authenticated/kas'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as AuthenticatedAdminOrganisasiRouteImport } from './routes/_authenticated/admin.organisasi'
import { Route as AuthenticatedAdminSiswaRouteImport } from './routes/_authenticated/admin.siswa'
import { Route as AuthenticatedAdminSaranRouteImport } from './routes/_authenticated/admin.saran'
import { Route as AuthenticatedAdminJadwalRouteImport } from './routes/_authenticated/admin.jadwal'
import { Route as AuthenticatedAdminAcaraRouteImport } from './routes/_authenticated/admin.acara'
import { Route as AuthenticatedAdminPortofolioRouteImport } from './routes/_authenticated/admin.portofolio'
import { Route as AuthenticatedAdminVotingRouteImport } from './routes/_authenticated/admin.voting'
import { Route as AuthenticatedAdminProfilRouteImport } from './routes/_authenticated/admin.profil'
import { Route as AuthenticatedAdminKasRouteImport } from './routes/_authenticated/admin.kas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const JadwalRoute = JadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => rootRouteImport,
} as any)
const PortofolioRoute = PortofolioRouteImport.update({
  id: '/portofolio',
  path: '/portofolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisasiRoute = OrganisasiRouteImport.update({
  id: '/organisasi',
  path: '/organisasi',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaRoute = SiswaRouteImport.update({
  id: '/siswa',
  path: '/siswa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVotingRoute = AuthenticatedVotingRouteImport.update({
  id: '/voting',
  path: '/voting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilSayaRoute = AuthenticatedProfilSayaRouteImport.update({
  id: '/profil-saya',
  path: '/profil-saya',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKasRoute = AuthenticatedKasRouteImport.update({
  id: '/kas',
  path: '/kas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaranRoute = AuthenticatedSaranRouteImport.update({
  id: '/saran',
  path: '/saran',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminOrganisasiRoute =
  AuthenticatedAdminOrganisasiRouteImport.update({
    id: '/organisasi',
    path: '/organisasi',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSiswaRoute = AuthenticatedAdminSiswaRouteImport.update({
  id: '/siswa',
  path: '/siswa',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSaranRoute = AuthenticatedAdminSaranRouteImport.update({
  id: '/saran',
  path: '/saran',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminJadwalRoute = AuthenticatedAdminJadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAcaraRoute = AuthenticatedAdminAcaraRouteImport.update({
  id: '/acara',
  path: '/acara',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminVotingRoute = AuthenticatedAdminVotingRouteImport.update({
  id: '/voting',
  path: '/voting',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProfilRoute = AuthenticatedAdminProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminKasRoute = AuthenticatedAdminKasRouteImport.update({
  id: '/kas',
  path: '/kas',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPortofolioRoute = AuthenticatedAdminPortofolioRouteImport.update({
  id: '/portofolio',
  path: '/portofolio',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/jadwal': typeof JadwalRoute
  '/organisasi': typeof OrganisasiRoute
  '/portofolio': typeof PortofolioRoute
  '/profil': typeof ProfilRoute
  '/setup': typeof SetupRoute
  '/siswa': typeof SiswaRoute
  '/saran': typeof AuthenticatedSaranRoute
  '/voting': typeof AuthenticatedVotingRoute
  '/profil-saya': typeof AuthenticatedProfilSayaRoute
  '/kas': typeof AuthenticatedKasRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/acara': typeof AuthenticatedAdminAcaraRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/jadwal': typeof AuthenticatedAdminJadwalRoute
  '/admin/organisasi': typeof AuthenticatedAdminOrganisasiRoute
  '/admin/portofolio': typeof AuthenticatedAdminPortofolioRoute
  '/admin/saran': typeof AuthenticatedAdminSaranRoute
  '/admin/voting': typeof AuthenticatedAdminVotingRoute
  '/admin/profil': typeof AuthenticatedAdminProfilRoute
  '/admin/kas': typeof AuthenticatedAdminKasRoute
  '/admin/siswa': typeof AuthenticatedAdminSiswaRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogIndexRoute
  '/jadwal': typeof JadwalRoute
  '/organisasi': typeof OrganisasiRoute
  '/portofolio': typeof PortofolioRoute
  '/profil': typeof ProfilRoute
  '/setup': typeof SetupRoute
  '/siswa': typeof SiswaRoute
  '/saran': typeof AuthenticatedSaranRoute
  '/voting': typeof AuthenticatedVotingRoute
  '/profil-saya': typeof AuthenticatedProfilSayaRoute
  '/kas': typeof AuthenticatedKasRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/acara': typeof AuthenticatedAdminAcaraRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/jadwal': typeof AuthenticatedAdminJadwalRoute
  '/admin/organisasi': typeof AuthenticatedAdminOrganisasiRoute
  '/admin/portofolio': typeof AuthenticatedAdminPortofolioRoute
  '/admin/saran': typeof AuthenticatedAdminSaranRoute
  '/admin/voting': typeof AuthenticatedAdminVotingRoute
  '/admin/profil': typeof AuthenticatedAdminProfilRoute
  '/admin/kas': typeof AuthenticatedAdminKasRoute
  '/admin/siswa': typeof AuthenticatedAdminSiswaRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/jadwal': typeof JadwalRoute
  '/organisasi': typeof OrganisasiRoute
  '/portofolio': typeof PortofolioRoute
  '/profil': typeof ProfilRoute
  '/setup': typeof SetupRoute
  '/siswa': typeof SiswaRoute
  '/_authenticated/saran': typeof AuthenticatedSaranRoute
  '/_authenticated/voting': typeof AuthenticatedVotingRoute
  '/_authenticated/profil-saya': typeof AuthenticatedProfilSayaRoute
  '/_authenticated/kas': typeof AuthenticatedKasRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/admin/acara': typeof AuthenticatedAdminAcaraRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/jadwal': typeof AuthenticatedAdminJadwalRoute
  '/_authenticated/admin/organisasi': typeof AuthenticatedAdminOrganisasiRoute
  '/_authenticated/admin/portofolio': typeof AuthenticatedAdminPortofolioRoute
  '/_authenticated/admin/saran': typeof AuthenticatedAdminSaranRoute
  '/_authenticated/admin/voting': typeof AuthenticatedAdminVotingRoute
  '/_authenticated/admin/profil': typeof AuthenticatedAdminProfilRoute
  '/_authenticated/admin/kas': typeof AuthenticatedAdminKasRoute
  '/_authenticated/admin/siswa': typeof AuthenticatedAdminSiswaRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/jadwal'
    | '/organisasi'
    | '/portofolio'
    | '/profil'
    | '/setup'
    | '/siswa'
    | '/saran'
    | '/voting'
    | '/profil-saya'
    | '/kas'
    | '/admin'
    | '/blog/$slug'
    | '/blog/'
    | '/admin/acara'
    | '/admin/blog'
    | '/admin/jadwal'
    | '/admin/organisasi'
    | '/admin/portofolio'
    | '/admin/saran'
    | '/admin/voting'
    | '/admin/profil'
    | '/admin/kas'
    | '/admin/siswa'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/jadwal'
    | '/organisasi'
    | '/portofolio'
    | '/profil'
    | '/setup'
    | '/siswa'
    | '/saran'
    | '/voting'
    | '/profil-saya'
    | '/kas'
    | '/blog/$slug'
    | '/admin/acara'
    | '/admin/blog'
    | '/admin/jadwal'
    | '/admin/organisasi'
    | '/admin/portofolio'
    | '/admin/saran'
    | '/admin/voting'
    | '/admin/profil'
    | '/admin/kas'
    | '/admin/siswa'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blog'
    | '/jadwal'
    | '/organisasi'
    | '/portofolio'
    | '/profil'
    | '/setup'
    | '/siswa'
    | '/_authenticated/saran'
    | '/_authenticated/voting'
    | '/_authenticated/profil-saya'
    | '/_authenticated/kas'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/blog/'
    | '/_authenticated/admin/acara'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/jadwal'
    | '/_authenticated/admin/organisasi'
    | '/_authenticated/admin/portofolio'
    | '/_authenticated/admin/saran'
    | '/_authenticated/admin/voting'
    | '/_authenticated/admin/profil'
    | '/_authenticated/admin/kas'
    | '/_authenticated/admin/siswa'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  JadwalRoute: typeof JadwalRoute
  OrganisasiRoute: typeof OrganisasiRoute
  PortofolioRoute: typeof PortofolioRoute
  ProfilRoute: typeof ProfilRoute
  SetupRoute: typeof SetupRoute
  SiswaRoute: typeof SiswaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jadwal': {
      id: '/jadwal'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof JadwalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portofolio': {
      id: '/portofolio'
      path: '/portofolio'
      fullPath: '/portofolio'
      preLoaderRoute: typeof PortofolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisasi': {
      id: '/organisasi'
      path: '/organisasi'
      fullPath: '/organisasi'
      preLoaderRoute: typeof OrganisasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa': {
      id: '/siswa'
      path: '/siswa'
      fullPath: '/siswa'
      preLoaderRoute: typeof SiswaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/saran': {
      id: '/_authenticated/saran'
      path: '/saran'
      fullPath: '/saran'
      preLoaderRoute: typeof AuthenticatedSaranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/voting': {
      id: '/_authenticated/voting'
      path: '/voting'
      fullPath: '/voting'
      preLoaderRoute: typeof AuthenticatedVotingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil-saya': {
      id: '/_authenticated/profil-saya'
      path: '/profil-saya'
      fullPath: '/profil-saya'
      preLoaderRoute: typeof AuthenticatedProfilSayaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kas': {
      id: '/_authenticated/kas'
      path: '/kas'
      fullPath: '/kas'
      preLoaderRoute: typeof AuthenticatedKasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/acara': {
      id: '/_authenticated/admin/acara'
      path: '/acara'
      fullPath: '/admin/acara'
      preLoaderRoute: typeof AuthenticatedAdminAcaraRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jadwal': {
      id: '/_authenticated/admin/jadwal'
      path: '/jadwal'
      fullPath: '/admin/jadwal'
      preLoaderRoute: typeof AuthenticatedAdminJadwalRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/saran': {
      id: '/_authenticated/admin/saran'
      path: '/saran'
      fullPath: '/admin/saran'
      preLoaderRoute: typeof AuthenticatedAdminSaranRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/voting': {
      id: '/_authenticated/admin/voting'
      path: '/voting'
      fullPath: '/admin/voting'
      preLoaderRoute: typeof AuthenticatedAdminVotingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/profil': {
      id: '/_authenticated/admin/profil'
      path: '/profil'
      fullPath: '/admin/profil'
      preLoaderRoute: typeof AuthenticatedAdminProfilRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kas': {
      id: '/_authenticated/admin/kas'
      path: '/kas'
      fullPath: '/admin/kas'
      preLoaderRoute: typeof AuthenticatedAdminKasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/portofolio': {
      id: '/_authenticated/admin/portofolio'
      path: '/portofolio'
      fullPath: '/admin/portofolio'
      preLoaderRoute: typeof AuthenticatedAdminPortofolioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/organisasi': {
      id: '/_authenticated/admin/organisasi'
      path: '/organisasi'
      fullPath: '/admin/organisasi'
      preLoaderRoute: typeof AuthenticatedAdminOrganisasiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/siswa': {
      id: '/_authenticated/admin/siswa'
      path: '/siswa'
      fullPath: '/admin/siswa'
      preLoaderRoute: typeof AuthenticatedAdminSiswaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAcaraRoute: typeof AuthenticatedAdminAcaraRoute
  AuthenticatedAdminJadwalRoute: typeof AuthenticatedAdminJadwalRoute
  AuthenticatedAdminSaranRoute: typeof AuthenticatedAdminSaranRoute
  AuthenticatedAdminVotingRoute: typeof AuthenticatedAdminVotingRoute
  AuthenticatedAdminProfilRoute: typeof AuthenticatedAdminProfilRoute
  AuthenticatedAdminKasRoute: typeof AuthenticatedAdminKasRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminOrganisasiRoute: typeof AuthenticatedAdminOrganisasiRoute
  AuthenticatedAdminPortofolioRoute: typeof AuthenticatedAdminPortofolioRoute
  AuthenticatedAdminSiswaRoute: typeof AuthenticatedAdminSiswaRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAcaraRoute: AuthenticatedAdminAcaraRoute,
  AuthenticatedAdminJadwalRoute: AuthenticatedAdminJadwalRoute,
  AuthenticatedAdminSaranRoute: AuthenticatedAdminSaranRoute,
  AuthenticatedAdminVotingRoute: AuthenticatedAdminVotingRoute,
  AuthenticatedAdminProfilRoute: AuthenticatedAdminProfilRoute,
  AuthenticatedAdminKasRoute: AuthenticatedAdminKasRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminOrganisasiRoute: AuthenticatedAdminOrganisasiRoute,
  AuthenticatedAdminPortofolioRoute: AuthenticatedAdminPortofolioRoute,
  AuthenticatedAdminSiswaRoute: AuthenticatedAdminSiswaRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedSaranRoute: typeof AuthenticatedSaranRoute
  AuthenticatedVotingRoute: typeof AuthenticatedVotingRoute
  AuthenticatedProfilSayaRoute: typeof AuthenticatedProfilSayaRoute
  AuthenticatedKasRoute: typeof AuthenticatedKasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedSaranRoute: AuthenticatedSaranRoute,
  AuthenticatedVotingRoute: AuthenticatedVotingRoute,
  AuthenticatedProfilSayaRoute: AuthenticatedProfilSayaRoute,
  AuthenticatedKasRoute: AuthenticatedKasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  JadwalRoute: JadwalRoute,
  OrganisasiRoute: OrganisasiRoute,
  PortofolioRoute: PortofolioRoute,
  ProfilRoute: ProfilRoute,
  SetupRoute: SetupRoute,
  SiswaRoute: SiswaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
